services:
  yonote:
    build: .
    container_name: huangsk/yonote:latest
    restart: always
    ports:
      - "5005:5005"
    environment:
      - SECRET_KEY=请替换为随机生成的密钥
      - ENCRYPTION_KEY=请替换为随机生成的加密密钥
      - ENCRYPTION_SALT=请替换为随机生成的盐值
    volumes:
      - ./data:/app/data
    networks:
      - notes_network

networks:
  notes_network:
    driver: bridge